### PR TITLE
mirror_lists.txt

### PR DESCRIPTION
**Pull request by daxinnan**
Add a new mirror site.

### CODE REVIEW

**Comment by daxinnan** [comment]
I don't know how to pull requests...

**Comment by Roger-luo** [comment]
You need to change the test, there's an assertion that checks the list of mirrors. Delete it.

**Comment by sunoru** [comment]
USTC's mirror doesn't work well with packages at present. I will merge this after https://github.com/ustclug/discussions/issues/253 is fixed.

**Comment by sunoru** [comment]
It's fixed now. I have updated the files by myself.

Thanks!

**Pull request closed without merging**
